### PR TITLE
Initial release

### PR DESCRIPTION
**Pull request by generationmake**
initial modifications for T07

### CODE REVIEW

**Comment by generationmake** [comment]
add some LED or head lamp

**Comment by generationmake** [comment]
Hi @aentinger and @wuehr1999 
could you please do a short review of the design.
Am I missing something important?
Thanks

**Comment by aentinger** [comment]
The Livox sensor should be probably mounted higher.

Please plan a snap-in place for the MandEye Dev kit, STL file should of current MandEye nose should be sent to you via email. When using snap-on Mandeye Dev Kit, the Livox will be mounted on top of the unit.

**Comment by wuehr1999** [comment]
Lgtm👍

**Comment by generationmake** [comment]
hi @aentinger 
could you please do a testprint of the mandeye holder?
Thanks

**Comment by aentinger** [comment]
> could you please do a testprint of the mandeye holder?

In the oven ... :moon_cake:

**Comment by aentinger** [comment]
IMG_20231016_060952_145
IMG_20231016_060940_333
IMG_20231016_060805_665

**Comment by aentinger** [comment]
Verdict of first iteration: "needs improvement" 😉 

The ramp that should gently press down the pogo pins when sliding the module on causes the pogo pins to block. Only when helping them gently with a screw-driver, the holder can be inserted more.

However, that's no help after the cut-out in the middle. Again the pogo pins are blocked from moving further (2nd ramp needed).

Also, the device can no longer be removed because there would also be a 3rd ramp needed when removing it.

Conclusio: Either have 3 perfectly fitting ramps or only one and leave enough space for the pogo pins to travel until they are pressed ...

**Comment by aentinger** [comment]
Suggestion: consider using counter-sunk head screws for mounting the rear wheel. (Basically plan in the space for the head of the screw). This allows mounting the rear wheel without any screw parts sticking out.

IMG_20231016_101523_874

**Comment by generationmake** [comment]
HI @aentinger 
could you please try the mandeye controller again?
Thanks

**Comment by generationmake** [comment]
> Suggestion: consider using counter-sunk head screws for mounting the rear wheel. (Basically plan in the space for the head of the screw). This allows mounting the rear wheel without any screw parts sticking out.
> 
> IMG_20231016_101523_874

Hi @aentinger 
The design is now the other way round with the screw nut at the top side. And this nut is some how sunk in. making it totally sink in would require to make the top layer thicker.

**Comment by aentinger** [comment]
> could you please try the mandeye controller again?

It's in the oven ... :cake:

**Comment by aentinger** [comment]
Looking good ;)

IMG_20231017_134819_191

**Comment by generationmake** [comment]
Hi @aentinger and @wuehr1999 
From my side this design is finished. Everything is included. STL files are up to date.
Please perform a review.
Thanks!

**Comment by aentinger** [comment]
Looks good to me :+1:

**Comment by wuehr1999** [comment]
LGTM

**Pull request merged**
