### PR TITLE
updated BOM links and readme

### LINKED ISSUE #2: [Bug Report] Links for components are out of date, please update
<a href="https://107-systems.org/"></a>

### :bug: Bug Report

The links to the components required to assemble the platform are partially out-dated, please provide working links.

### PR DESCRIPTION
**Pull request by generationmake**

### CODE REVIEW

**Comment by generationmake** [comment]
Hi @aentinger 
Could you please check the links and sources?
Do you know better sources? Do we need to exchange anything?

**Review by aentinger — APPROVED** [review]
LGTM 👍

**Comment by aentinger** [comment]
Hi @generationmake ☕ 👋 

I was thinking of having a wheel without air inside (which consequently can't be compressed, as compression would change the wheel diameter and lead to errors in odometry and closed loop velocity control), smth like this one: https://eu.robotshop.com/products/devantech-125mm-wheel

What do you think?

**Comment by generationmake** [comment]
If you want to go outside and into terrain you need air filled tires because otherwise they will loose grip. So we will definitely need on option with air filled tires.

if you only want to use it inside on even and hard floors rubber wheels are definitely the better choice. But then I would suggest to use a smaller roller wheel and smaller wheels. Like these ones:

https://www.pollin.de/p/masterproof-lenkrolle-kugelgelagert-4054-pvc-oe-50-mm-490596
https://eu.robotshop.com/products/70mm-aluminium-wheel-6mm-bore

**Comment by aentinger** [comment]
>If you want to go outside and into terrain you need air filled tires because otherwise they will loose grip. So we will definitely need on option with air filled tires.

I agree with you.

>https://www.pollin.de/p/masterproof-lenkrolle-kugelgelagert-4054-pvc-oe-50-mm-490596
https://eu.robotshop.com/products/70mm-aluminium-wheel-6mm-bore

Would those fit on the current design (i.e. would there still be a non-zero ground clearance)?

Also: please add those links to the BOM 🙏

**Comment by generationmake** [comment]
This should work with the current design. The only problem could be the battery.
I will check it with the 3d model.

**Comment by generationmake** [comment]
Hi.
I added a 3d modell of the battery. But his model needs to be verified.
I added a rendering of the side view.
It seems like we may run into problems with the smaller wheels. I will think about it again.

**Comment by aentinger** [comment]
>It seems like we may run into problems with the smaller wheels. I will think about it again.

Are there any updates on this?

**Pull request merged**
