### PR TITLE
update to rev 0.3

### LINKED ISSUE #11: [Feature Request] Increase width/length of top-plate of motorcover in order to fully cover the main chassis
<a href="https://107-systems.org/"></a>

### ⚡ Feature Request

Increase width/length of top-plate of [motorcover ](https://github.com/107-systems/T07/blob/main/productiondata/motorcover.stl)in order to fully cover the main chassis. No gap should be visible.

WhatsApp Image 2024-01-13 at 18 03 10 (1)

### LINKED ISSUE #12: [Bug Report] Provide bigger cut-outs for motor in bottom plate (collission)
<a href="https://107-systems.org/"></a>

### :bug: Bug Report

IMG_20240119_105531_366

### LINKED ISSUE #13: [Bug Report] Loose fit of MandEye Dev-Kit
<a href="https://107-systems.org/"></a>

### :bug: Bug Report

**Describe the bug**

With the latest version of the mandeye holder the MandEye Dev Kit is sitting very loosely in the holder and can easily fall out. A tighter fill will be needed.

### PR DESCRIPTION
**Pull request by generationmake**
fix some minor issues of rev 0.2

### CODE REVIEW

**Comment by generationmake** [comment]
hi @aentinger 
could you give the new motorcover a try?
Thanks

**Comment by aentinger** [comment]
Hi @generationmake :coffee: :wave: 

The new version of the MandEye-Holder is too tight, the previous version too loose. I suggest taking the middle way between those two.

**V1**
2024-01-21-MandEye-Holder-Test-Print-V1

**V2**
2024-01-21-MandEye-Holder-Test-Print-V2

**Comment by aentinger** [comment]
The new motor cover is looking good ;)

IMG_20240125_051716_713
IMG_20240125_051657_292

**Comment by aentinger** [comment]
Ping @generationmake re angled MandEye holder :wink:

**Pull request merged**
